# Generated by Django 2.1.7 on 2019-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantdailyrecord',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantsalesrecords',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
