# Generated by Django 2.1.7 on 2019-04-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20190408_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantdailyrecord',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_record', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='merchantsalesrecords',
            name='merchant_daily_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_sales', to='merchant.MerchantDailyRecord'),
        ),
    ]
