# Generated by Django 2.1.7 on 2019-04-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190410_1642'),
        ('merchant', '0003_auto_20190409_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='common.City'),
        ),
    ]
