# Generated by Django 2.1.7 on 2019-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_merchant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantdailyrecord',
            name='mid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
