# Generated by Django 2.1.7 on 2020-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_merchantdailyrecord_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='shop_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
