# Generated by Django 2.1.7 on 2020-04-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20200426_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='shop_address',
        ),
    ]
