# Generated by Django 2.1.7 on 2020-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_remove_merchant_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantdailyrecord',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
