# Generated by Django 2.1.7 on 2020-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_merchantdailyrecord_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
