# Generated by Django 2.1.7 on 2020-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_remove_merchantdailyrecord_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantdailyrecord',
            name='item_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
