# Generated by Django 2.1.7 on 2020-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_merchantdailyrecord_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantdailyrecord',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
