# Generated by Django 2.1.7 on 2020-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0014_merchantsalesrecords_after_per_t_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantsalesrecords',
            name='after_per_t_amount',
        ),
        migrations.AddField(
            model_name='merchantsalesrecords',
            name='after_per_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
