# Generated by Django 2.1.7 on 2019-04-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0004_merchant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], default='Pending', max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('is_payment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Awaiting_Payment', 'Awaiting_Payment'), ('Cancelled', 'Cancelled'), ('Awaiting_Fullfillment', 'Awaiting_Fullfillment'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='Pending', max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_oder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('item_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('merchant_daily_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_daily_record', to='merchant.MerchantDailyRecord')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='client.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Error', 'Error'), ('Declined', 'Declined'), ('rejected', 'rejected')], default='Accepted', max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='client.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='client.Order'),
        ),
    ]
