# Generated by Django 2.1.7 on 2019-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190418_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
