# Generated by Django 2.1.7 on 2019-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_invoice_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
