# Generated by Django 2.1.7 on 2019-05-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_userprofile_city'),
        ('client', '0006_order_alternate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_city', to='common.City'),
        ),
    ]
