# Generated by Django 2.1.7 on 2020-04-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20190601_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
