# Generated by Django 2.1.7 on 2020-05-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200502_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='percentage_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
