# Generated by Django 2.1.7 on 2020-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_invoice_percentage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='after_per_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
