# Generated by Django 2.1.7 on 2019-04-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('facebook_profile_url', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=256, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_custom_profile_image', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('type', models.IntegerField(blank=True, choices=[('Company', 'Company'), ('client', 'Client'), ('Corporate', 'Corporate')], default='Company', null=True)),
                ('hometown', models.CharField(blank=True, max_length=256, null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
