# Generated by Django 2.1.7 on 2019-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190410_1642'),
        ('common', '0004_auto_20190404_1505'),
    ]

    operations = [
    ]
