# Generated by Django 2.1.7 on 2019-04-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userprofile_address'),
        ('common', '0005_merge_20190419_1158'),
    ]

    operations = [
    ]
